import Anthropic from '@anthropic-ai/sdk';
import { CaseFile } from '../types/caseFile';
import { searchGuidelines } from './search';

const anthropic = new Anthropic({
  apiKey: process.env.ANTHROPIC_API_KEY,
});

export async function runQAAgent(caseFile: CaseFile): Promise<string> {
  const lastMsg = caseFile.transcript[caseFile.transcript.length - 1];
  if (!lastMsg || lastMsg.speaker !== 'user') return "No question found.";

  const userQuery = lastMsg.text;

  // 1. Quick translation to English if needed (for better search)
  let englishQuery = userQuery;
  if (caseFile.language === 'ml') {
    try {
      const transRes = await anthropic.messages.create({
        model: 'claude-3-5-haiku-latest',
        max_tokens: 50,
        messages: [{ role: 'user', content: `Translate this Malayalam/Manglish text to English for search keywords: "${userQuery}". ONLY output the English keywords, nothing else.` }]
      });
      englishQuery = transRes.content[0].type === 'text' ? transRes.content[0].text : userQuery;
    } catch (e) {
      console.warn("Translation failed, using original query");
    }
  }

  // 2. Search Guidelines
  const searchResults = searchGuidelines(englishQuery, 5);
  
  if (searchResults.length === 0 || searchResults[0].score < 1) {
    caseFile.agent_log.push({
      agent: 'Q&A Agent',
      action: `Searched guidelines for "${englishQuery}", no good matches found.`,
      timestamp: new Date().toISOString()
    });
    
    // We didn't find anything, fallback immediately
    const fallbackText = caseFile.language === 'ml' 
      ? "ഔദ്യോഗിക മാർഗ്ഗനിർദ്ദേശങ്ങളിൽ എനിക്കിത് കണ്ടെത്താനായില്ല. നിങ്ങളെ ഒരു സോഷ്യൽ വർക്കറുമായി ബന്ധിപ്പിക്കാൻ ഞാൻ സഹായിക്കട്ടേ?"
      : "I couldn't find this in the official guidelines. Would you like me to connect you with a social worker?";
      
    caseFile.transcript.push({
      speaker: 'agent',
      text: fallbackText,
      timestamp: new Date().toISOString()
    });
    
    return fallbackText;
  }

  caseFile.agent_log.push({
    agent: 'Q&A Agent',
    action: `Searched guidelines for "${englishQuery}", found ${searchResults.length} matching sections (e.g. ${searchResults[0].chunk.sourceDocument}).`,
    timestamp: new Date().toISOString()
  });

  // 3. Construct prompt for Sonnet
  const contextText = searchResults.map(r => `--- SOURCE: ${r.chunk.sourceDocument} | SECTION: ${r.chunk.section} ---\n${r.chunk.content}`).join('\n\n');
  
  const systemPrompt = `You are a helpful Government Schemes Q&A Assistant.
Rules:
1. Answer the user's question ONLY using the provided context chunks.
2. If the context chunks don't clearly answer the question, say exactly: "I couldn't find this in the official guidelines. Would you like me to connect you with a social worker?"
3. Answer in the user's chosen language (${caseFile.language}). Handle Manglish naturally.
4. Keep the answer to 2-4 simple sentences suitable for speaking aloud.
5. Mention the source naturally (e.g. "According to Section X of...").
6. STRICT: NEVER guess, never decide or hint at eligibility, never promise benefits, never add facts not in the context.`;

  try {
    const response = await anthropic.messages.create({
      model: 'claude-3-5-sonnet-latest',
      max_tokens: 300,
      system: systemPrompt,
      messages: [
        { role: 'user', content: `Context:\n${contextText}\n\nQuestion: ${userQuery}` }
      ],
    });

    const reply = response.content[0].type === 'text' ? response.content[0].text : 'Error generating answer.';

    // Check if it's the fallback text generated by the LLM
    const isFallback = reply.includes("couldn't find this") || reply.includes("സോഷ്യൽ വർക്കറുമായി") || reply.includes("social worker");

    const sourcesToSave = isFallback ? undefined : searchResults.map(r => ({
      sourceDocument: r.chunk.sourceDocument,
      section: r.chunk.section,
      content: r.chunk.content,
      isDemo: r.chunk.isDemo
    }));

    caseFile.transcript.push({
      speaker: 'agent',
      text: reply,
      timestamp: new Date().toISOString(),
      sources: sourcesToSave
    });

    return reply;

  } catch (err: any) {
    console.error('Q&A Agent error:', err);
    return 'Sorry, I had trouble searching the guidelines right now.';
  }
}
